[package]
name = "rsgenetic"
version = "1.1.0"
authors = ["Mathieu De Coster <mth.decoster@gmail.com>"]
description = "A library providing genetic algorithm execution."
repository = "https://github.com/m-decoster/RsGenetic"
readme = "README.md"
keywords = ["genetic", "algorithm", "evolution"]
license = "Apache-2.0"
documentation = "http://m-decoster.github.io/RsGenetic"

[dependencies]
rand = "0.3"
time = "0.1"
